DOMAIN = "z2z_librus"
PLATFORMS = ["sensor", "calendar"]

CONF_SCAN_INTERVAL = "scan_interval"
DEFAULT_SCAN_INTERVAL = 30

CONF_LUNCH_ENABLED = "lunch_enabled"
CONF_LUNCH_TIME = "lunch_time"
DEFAULT_LUNCH_ENABLED = True
DEFAULT_LUNCH_TIME = "11:45:00"
LUNCH_DURATION_MINUTES = 15
